plugins {
  id 'com.google.cloud.tools.jib' version '3.3.2'
}

jib {
  from {
    image = "amazoncorretto:19"
  }
  to {
    image = "file-backup-s3:latest"
  }
  container {
    mainClass = 'com.willmolloy.backup.s3.Main'
    environment(Map.of("SOURCE_PATH", "/source", "DESTINATION_BUCKET", "", "DESTINATION_BUCKET_PREFIX", "/"))
    creationTime = getGitCommitTime()
    jvmFlags = ['--enable-preview']
  }
}

static def getGitCommitTime() {
  String[] parts = 'git show -s --format=%ci'.execute().text.trim().split(" ")
  return (parts[0]+'T'+parts[1]+parts[2])
}

dependencies {
  implementation project(":file-backup-core")
  implementation project(":file-backup-local")
  implementation group: 'software.amazon.awssdk', name: 's3', version: '2.20.77'
}