plugins {
  id 'com.google.cloud.tools.jib' version '3.3.2'
}

jib {
  from {
    image = "amazoncorretto:19"
  }
  to {
    image = "ghcr.io/will-molloy/file-backup-local"
  }
  container {
    mainClass = 'com.willmolloy.backup.local.Main'
    environment(Map.of("SOURCE_PATH", "/source", "DESTINATION_PATH", "/destination"))
    creationTime = getGitCommitTime()
    jvmFlags = ['--enable-preview']
  }
}

static def getGitCommitTime() {
  String[] parts = 'git show -s --format=%ci'.execute().text.trim().split(" ")
  return (parts[0]+'T'+parts[1]+parts[2])
}

dependencies {
  implementation project(":file-backup-core")
}