plugins {
  id 'com.google.cloud.tools.jib' version '3.3.2'
}

jib {
  from {
    image = "amazoncorretto:19"
  }
  to {
    image = "ghcr.io/will-molloy/file-sync-s3"
  }
  container {
    mainClass = 'com.willmolloy.sync.s3.Main'
    environment(Map.of("SOURCE_PATH", "/source", "DESTINATION_BUCKET", "", "DESTINATION_BUCKET_PREFIX", "/"))
    creationTime = getGitCommitTime()
    jvmFlags = ['--enable-preview', '--add-modules', 'jdk.incubator.concurrent']
  }
}

static def getGitCommitTime() {
  String[] parts = 'git show -s --format=%ci'.execute().text.trim().split(" ")
  return (parts[0]+'T'+parts[1]+parts[2])
}

dependencies {
  implementation project(":file-sync-core")
  implementation project(":file-sync-local")
  implementation group: 'software.amazon.awssdk', name: 's3', version: '2.20.93'
}